
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "BerkeleyMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BerkeleyMono Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
decorations = "None"
padding.x = 14
padding.y = 14
